import { readFileSync } from 'node:fs'

import { describe, expect, it } from 'vitest'

import { KNOWLEDGE } from '@/lib/ai/knowledge'
import { buildInstructions } from '@/lib/ai/prompt'

describe('what the assistant knows', () => {
  it('matches the markdown people review it in', () => {
    // lib/ai/knowledge.ts is the source - the prompt is built from it, and
    // a serverless function cannot read a markdown file from the repo. The
    // markdown is the copy a person argues with, generated by
    // `bun run ai-knowledge`. Edit the TypeScript and re-run it; this test is
    // what notices when only one of the two moved.
    expect(readFileSync('docs/ai/knowledge.md', 'utf8')).toBe(KNOWLEDGE)
  })

  it('still says the things the assistant must never contradict', () => {
    // These are the load-bearing claims. A rewrite of the knowledge that
    // loses one of them changes what the assistant tells people about
    // identity theft and about what it cannot see.
    for (const claim of ['fødselsnummer', 'Reverse chronological', 'It does not grade people']) {
      expect(KNOWLEDGE, `knowledge.ts no longer mentions ${claim}`).toContain(claim)
    }
  })
})

describe('the instruction prefix', () => {
  it('is identical on every call, so the cache can match it', () => {
    // Prompt caching matches the longest common prefix. A date, a locale or a
    // CV id interpolated in here would bust the cache for everybody and turn
    // a 94% discount into full price.
    expect(buildInstructions()).toBe(buildInstructions())
  })

  it('puts the rules before the knowledge', () => {
    const instructions = buildInstructions()

    expect(instructions.indexOf('Regler:')).toBeLessThan(instructions.indexOf(KNOWLEDGE))
  })

  it('tells the model the identifiers were removed, not missing', () => {
    // Without this it asks the user for the name it cannot see, which reads
    // as a bug in the CV rather than a deliberate redaction.
    expect(buildInstructions()).toContain('[navn]')
  })
})
