import type { CvLabels } from './types'

export const en: CvLabels = {
  sections: {
    summary: 'Profile',
    experience: 'Work Experience',
    education: 'Education',
    skills: 'Skills',
    languages: 'Languages',
    certifications: 'Certifications',
    projects: 'Projects',
    courses: 'Courses',
    volunteering: 'Volunteering',
    interests: 'Interests',
    drivingLicence: 'Driving Licence',
    references: 'References',
    custom: 'Custom',
  },
  skillLevels: {
    1: 'Beginner',
    2: 'Basic',
    3: 'Intermediate',
    4: 'Advanced',
    5: 'Expert',
  },
  languageLevels: {
    a1: 'A1',
    a2: 'A2',
    b1: 'B1',
    b2: 'B2',
    c1: 'C1',
    c2: 'C2',
    native: 'Native',
  },
  present: 'Present',
  months: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ],
  referencesOnRequest: 'References available on request',
  drivingLicenceClass: 'Class',
}
