import type { CvLabels } from './types'

export const no: CvLabels = {
  sections: {
    summary: 'Om meg',
    experience: 'Arbeidserfaring',
    education: 'Utdanning',
    skills: 'Ferdigheter',
    languages: 'Språk',
    certifications: 'Sertifiseringer',
    projects: 'Prosjekter',
    courses: 'Kurs',
    volunteering: 'Frivillig arbeid',
    interests: 'Interesser',
    drivingLicence: 'Førerkort',
    references: 'Referanser',
    custom: 'Egendefinert',
  },
  skillLevels: {
    1: 'Nybegynner',
    2: 'Grunnleggende',
    3: 'Middels',
    4: 'Avansert',
    5: 'Ekspert',
  },
  languageLevels: {
    a1: 'A1',
    a2: 'A2',
    b1: 'B1',
    b2: 'B2',
    c1: 'C1',
    c2: 'C2',
    native: 'Morsmål',
  },
  present: 'nå',
  months: [
    'jan.',
    'feb.',
    'mar.',
    'apr.',
    'mai',
    'jun.',
    'jul.',
    'aug.',
    'sep.',
    'okt.',
    'nov.',
    'des.',
  ],
  referencesOnRequest: 'Referanser oppgis ved forespørsel',
  drivingLicenceClass: 'Klasse',
}
